### ISSUE TITLE
HCP atlas - which auditory cortex regions?

### ISSUE THREAD

**Issue by PeerHerholz** [C0C0AN/ALPACA#7]
Hi, 

I'm currently working on the [freesurfer fsaverage version of the hcp atlas](https://figshare.com/articles/HCP-MMP1_0_projected_on_fsaverage/3498446) and wondering which auditory (temporal) cortex regions to include/extract for ALPACA.

The complete atlas looks like this:
![hcp_complete](https://user-images.githubusercontent.com/20129524/41787246-0dd6c68e-7648-11e8-9b95-fe1a4539f908.png)

So far I would include/extract the following regions:
A1, A4, A5, LBelt, MBelt, PBelt, STGa, STSda, STSdp, STSva, STSvp and TA2 which results in something like this (including complete annotation outlines):
![hcp_auditory_annot](https://user-images.githubusercontent.com/20129524/41787394-945e95c4-7648-11e8-8d3d-02abc18f31a6.png)

or this (without complete annotation outlines):
![hcp_auditory](https://user-images.githubusercontent.com/20129524/41787410-a4bdfc7a-7648-11e8-8c07-cc463ae4b57f.png)

What do you think? Include more/less/different regions?

**Comment by ofgulban** [comment]
I think the auditory regions that you have selected are good. I am not very familiar with the ones outside of Hescl's Gyrus though, so those are your call :).

**Comment by PeerHerholz** [comment]
Thx @ofgulban for the feedback. Haha, me neither. I guess we could also just include those for now and add others later on, but I also think that everything else won't be "auditory cortex" but rather temporal cortex, so within ALPACA it should be okay. @M-earnest1 does this work for you as well?

**Comment by M-earnest** [comment]
I would also agree, it seems that your choice encompasses all relevant areas, at least to what little knowledge i have of the subject.

**Comment by PeerHerholz** [comment]
KK, thx.

I just uploaded the ROIs (details [here](https://github.com/C0C0AN/ALPACA/commit/8965d8e02c5f4aeb0510a818afc180510bc030a2)).

**Comment by PeerHerholz** [comment]
Add on:

I checked the original [HCP atlas](https://www.nature.com/articles/nature18933) again. 
They have some amazing stuff in the supplementals, for example also detailed descriptions on [how different regions were parcellated](https://media.nature.com/original/nature-assets/nature/journal/v536/n7615/extref/nature18933-s3.pdf). The auditory section (among the rest) is a very good and informative read. Based on that I thought about including the rostral part of the insula. I uploaded these ROIs as well (details [here](https://github.com/C0C0AN/ALPACA/commit/e1789ceaae19a8bb306619855e41074652ec731a)).
